# Generated by Django 2.2.6 on 2019-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('ot', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
